### ISSUE TITLE
Create documentation for the api

### ISSUE THREAD

**Issue by ankan17** [lugnitdgp/glug_website_backend#4]
Look at any good api documentation and create one for this repo. Also document your code, wherever possible.

**Comment by realsdx** [comment]
Is it required? as all API views is listed on the Api-Root of DRF

**Comment by ankan17** [comment]
Yes, it is necessary. Apart from listing all the endpoints, you also need to mention the data returned at that endpoint. People will see the documentation first, not the API root of DRF.

**Comment by arc9693** [comment]
I would like to get assigned for this.

**Comment by realsdx** [comment]
> I would like to get assigned for this.

Use can Postman for generating API documentation
